export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const CLEAR_DATA_TOKEN = "CLEAR_DATA_TOKEN";

export const FECTH_PRODUCT_REQUEST = "FECTH_PRODUCT_REQUEST";
export const FECTH_PRODUCT_SUCCESS = "FECTH_PRODUCT_SUCCESS";
export const FECTH_PRODUCT_FAILURE = "FECTH_PRODUCT_FAILURE";

export const FECTH_CATEGORY_REQUEST = "FECTH_CATEGORY_REQUEST";
export const FECTH_CATEGORY_SUCCESS = "FECTH_CATEGORY_SUCCESS";
export const FECTH_CATEGORY_FAILURE = "FECTH_CATEGORY_FAILURE";

export const FECTH_STORE_REQUEST = "FECTH_STORE_REQUEST";
export const FECTH_STORE_SUCCESS = "FECTH_STORE_SUCCESS";
export const FECTH_STORE_FAILURE = "FECTH_STORE_FAILURE";

export const FECTH_CUSTOMER_REQUEST = "FECTH_CUSTOMER_REQUEST";
export const FECTH_CUSTOMER_SUCCESS = "FECTH_CUSTOMER_SUCCESS";
export const FECTH_CUSTOMER_FAILURE = "FECTH_CUSTOMER_FAILURE";

export const FECTH_STAFF_REQUEST = "FECTH_STAFF_REQUEST";
export const FECTH_STAFF_SUCCESS = "FECTH_STAFF_SUCCESS";
export const FECTH_STAFF_FAILURE = "FECTH_STAFF_FAILURE";

export const FECTH_DETAIL_PRODUCT_REQUEST = "FECTH_DETAIL_PRODUCT_REQUEST";
export const FECTH_DETAIL_PRODUCT_SUCCESS = "FECTH_DETAIL_PRODUCT_SUCCESS";
export const FECTH_DETAIL_PRODUCT_FAILURE = "FECTH_DETAIL_PRODUCT_FAILURE";

export const FECTH_BANNER_REQUEST = "FECTH_BANNER_REQUEST";
export const FECTH_BANNER_SUCCESS = "FECTH_BANNER_SUCCESS";
export const FECTH_BANNER_FAILURE = "FECTH_BANNER_FAILURE";

export const FECTH_MY_INFO_REQUEST = "FECTH_MY_INFO_REQUEST";
export const FECTH_MY_INFO_SUCCESS = "FECTH_MY_INFO_SUCCESS";
export const FECTH_MY_INFO_FAILURE = "FECTH_MY_INFO_FAILURE";
export const FECTH_MY_INFO_UPDATE_REQUEST = "FECTH_MY_INFO_UPDATE_REQUEST";
export const FECTH_MY_INFO_UPDATE_SUCCESS = "FECTH_MY_INFO_UPDATE_SUCCESS";
export const FECTH_MY_INFO_UPDATE_FAILURE = "FECTH_MY_INFO_UPDATE_FAILURE";

export const FECTH_INVOICE_REQUEST = "FECTH_INVOICE_REQUEST";
export const FECTH_INVOICE_SUCCESS = "FECTH_INVOICE_SUCCESS";
export const FECTH_INVOICE_FAILURE = "FECTH_INVOICE_FAILURE";

export const FECTH_STATICTIS_PRODUCT_REQUEST =
  "FECTH_STATICTIS_PRODUCT_REQUEST";
export const FECTH_STATICTIS_PRODUCT_SUCCESS =
  "FECTH_STATICTIS_PRODUCT_SUCCESS";
export const FECTH_STATICTIS_PRODUCT_FAILURE =
  "FECTH_STATICTIS_PRODUCT_FAILURE";

export const FECTH_STATICTIS_CUSTOMER_REQUEST =
  "FECTH_STATICTIS_CUSTOMER_REQUEST";
export const FECTH_STATICTIS_CUSTOMER_SUCCESS =
  "FECTH_STATICTIS_CUSTOMER_SUCCESS";
export const FECTH_STATICTIS_CUSTOMER_FAILURE =
  "FECTH_STATICTIS_CUSTOMER_FAILURE";

export const FECTH_STATICTIS_REVENUE_REQUEST =
  "FECTH_STATICTIS_REVENUE_REQUEST";
export const FECTH_STATICTIS_REVENUE_SUCCESS =
  "FECTH_STATICTIS_REVENUE_SUCCESS";
export const FECTH_STATICTIS_REVENUE_FAILURE =
  "FECTH_STATICTIS_REVENUE_FAILURE";
